program: virus.py
method: bayes
metric:
  name: loss
  goal: minimize
parameters:
  percentage:
    value: 0.97
  lr:
    distribution: log_uniform
    min: 0.0001
    max: 0.01
  batch_size: 
    value: 25
  n_epochs: 
    value: 60
  